spring.application.name=10_PROEUN_PHATSA_SPRING_HOMEWORK002

spring.datasource.url=jdbc:postgresql://localhost:5432/post_db
spring.datasource.username=postgres
spring.datasource.password=phatsa08

springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
mybatis.configuration.map-underscore-to-camel-case=true
server.port=9090
